-- 101_backfill_users.sql
-- Phase 2 / Backfill
-- Populate users from legacy guerreros.

SET NAMES utf8mb4;

INSERT INTO users (
    legacy_user_id,
    full_name,
    display_name,
    birth_date,
    age,
    gender,
    shirt_size,
    coming_from,
    whatsapp,
    email,
    allergies,
    reasons,
    guardian_phone,
    church,
    registered_at,
    guardian_name,
    facebook,
    instagram,
    accepted_policies,
    password_hash,
    medications,
    phone,
    verification_code,
    guardian_email,
    user_status
)
SELECT
    g.id AS legacy_user_id,
    COALESCE(NULLIF(TRIM(g.nombre), ''), CONCAT('legacy-user-', g.id)) AS full_name,
    NULLIF(TRIM(g.nick), '') AS display_name,
    g.fechanac AS birth_date,
    g.edad AS age,
    NULLIF(TRIM(g.sexo), '') AS gender,
    NULLIF(TRIM(g.talla), '') AS shirt_size,
    NULLIF(TRIM(g.vienede), '') AS coming_from,
    NULLIF(TRIM(g.whatsapp), '') AS whatsapp,
    NULLIF(TRIM(g.email), '') AS email,
    NULLIF(TRIM(g.alergias), '') AS allergies,
    NULLIF(TRIM(g.razones), '') AS reasons,
    NULLIF(TRIM(g.contacto_tutor), '') AS guardian_phone,
    NULLIF(TRIM(g.iglesia), '') AS church,
    g.fechahora_registro AS registered_at,
    NULLIF(TRIM(g.tutor_nombre), '') AS guardian_name,
    NULLIF(TRIM(g.facebook), '') AS facebook,
    NULLIF(TRIM(g.instagram), '') AS instagram,
    IFNULL(CAST(g.politicas AS UNSIGNED), 0) AS accepted_policies,
    NULLIF(TRIM(g.password), '') AS password_hash,
    NULLIF(TRIM(g.medicamentos), '') AS medications,
    NULLIF(TRIM(g.telefono), '') AS phone,
    NULLIF(TRIM(g.codigo), '') AS verification_code,
    NULLIF(TRIM(g.email_tutor), '') AS guardian_email,
    NULL AS user_status
FROM guerreros g
ON DUPLICATE KEY UPDATE
    full_name = VALUES(full_name),
    display_name = VALUES(display_name),
    birth_date = VALUES(birth_date),
    age = VALUES(age),
    gender = VALUES(gender),
    shirt_size = VALUES(shirt_size),
    coming_from = VALUES(coming_from),
    whatsapp = VALUES(whatsapp),
    email = VALUES(email),
    allergies = VALUES(allergies),
    reasons = VALUES(reasons),
    guardian_phone = VALUES(guardian_phone),
    church = VALUES(church),
    registered_at = VALUES(registered_at),
    guardian_name = VALUES(guardian_name),
    facebook = VALUES(facebook),
    instagram = VALUES(instagram),
    accepted_policies = VALUES(accepted_policies),
    password_hash = VALUES(password_hash),
    medications = VALUES(medications),
    phone = VALUES(phone),
    verification_code = VALUES(verification_code),
    guardian_email = VALUES(guardian_email);
